//! Export of a flash plan as a script: `*.cmd` on Windows, `*.sh` elsewhere.
//!
//! The script is a plain transcription of the procedures that are about to be
//! flashed (and the standalone erases), so the same flash can be repeated,
//! checked by hand, or run on a machine without the app. Only the tool's own
//! command line is used — which is why the built-in fastboot, that has none,
//! is written out as `fastboot` from the Android platform-tools.
//!
//! Comments are English, like every other generated file: they are part of
//! the script, not of the interface.

use crate::flash_engine::Engine;
use crate::flashfile::{FlashOp, FlashPackage};

/// The shell a script is written for; the host decides which one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shell {
    /// Windows `cmd.exe`.
    Cmd,
    /// POSIX `sh`.
    Sh,
}

impl Shell {
    /// The shell of the machine the app runs on.
    pub fn for_host() -> Self {
        if cfg!(windows) {
            Self::Cmd
        } else {
            Self::Sh
        }
    }

    /// Extension of the script, without the dot.
    pub fn extension(self) -> &'static str {
        match self {
            Self::Cmd => "cmd",
            Self::Sh => "sh",
        }
    }

    /// Name offered in the save dialog, e.g. `XT2451-2_flash.cmd`.
    pub fn file_name(self, model: Option<&str>) -> String {
        match model.map(sanitize).filter(|model| !model.is_empty()) {
            Some(model) => format!("{model}_flash.{}", self.extension()),
            None => format!("flash.{}", self.extension()),
        }
    }

    /// The marker that starts a comment line.
    fn comment(self) -> &'static str {
        match self {
            Self::Cmd => "REM",
            Self::Sh => "#",
        }
    }

    /// Quotes one value for this shell.
    fn quote(self, value: &str) -> String {
        match self {
            // `%` starts a variable in a batch file, so it has to be doubled.
            Self::Cmd => format!("\"{}\"", value.replace('%', "%%")),
            // Inside double quotes only these three keep their meaning.
            Self::Sh => {
                let escaped = value
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('$', "\\$")
                    .replace('`', "\\`");

                format!("\"{escaped}\"")
            }
        }
    }
}

/// Everything the script is written from.
pub struct ScriptJob<'a> {
    pub package: &'a FlashPackage,
    /// The procedures that will run (the checked ones, in package order).
    pub steps: &'a [FlashOp],
    /// Erases the "Erase …" buttons added on top of the package.
    pub extra_erases: &'a [String],
    /// The tool the app would flash with, so the script starts the same one.
    /// A built-in flash has no command line, so it becomes `fastboot`.
    pub engine: &'a Engine,
    /// Device the script addresses; empty writes it without `-s`.
    pub serial: &'a str,
    pub shell: Shell,
}

/// Renders the script.
pub fn render(job: &ScriptJob<'_>) -> String {
    let shell = job.shell;
    let comment = shell.comment();
    let mut out = String::new();

    if shell == Shell::Sh {
        out.push_str("#!/bin/sh\n");
    } else {
        out.push_str("@echo off\n");
    }

    // What the script does and where its images are.
    let firmware = match (&job.package.model, &job.package.software_version) {
        (Some(model), Some(version)) => format!("{model} ({version})"),
        (Some(model), None) => model.clone(),
        (None, Some(version)) => version.clone(),
        (None, None) => "the firmware package".to_owned(),
    };

    out.push_str(&format!(
        "{comment} Flash script for {firmware}, generated by LMN Flash.\n"
    ));
    out.push_str(&format!(
        "{comment} {selected} of the {total} procedures of the package are written below{erases}.\n",
        selected = job.steps.len(),
        total = job.package.steps.len(),
        erases = match job.extra_erases.len() {
            0 => String::new(),
            1 => ", followed by one extra erase".to_owned(),
            count => format!(", followed by {count} extra erases"),
        },
    ));
    out.push_str(&format!(
        "{comment} The images are read from the folder below; change the line if they\n\
         {comment} are somewhere else (a package opened from a ZIP is unpacked into a\n\
         {comment} temporary folder, which may be gone by now).\n",
    ));

    match shell {
        Shell::Cmd => out.push_str(&format!(
            "cd /d {}\n",
            shell.quote(&job.package.directory.display().to_string())
        )),
        Shell::Sh => out.push_str(&format!(
            "cd {}\n",
            shell.quote(&job.package.directory.display().to_string())
        )),
    }

    // The tool, and the device when one was selected.
    out.push('\n');
    out.push_str(&format!(
        "{comment} Tool and device: edit these lines, not the commands below.\n"
    ));

    let (tool, tool_note) = tool_of(job.engine);
    match shell {
        Shell::Cmd => out.push_str(&format!("set \"MFASTBOOT={tool}\"\n")),
        Shell::Sh => out.push_str(&format!("MFASTBOOT={}\n", shell.quote(&tool))),
    }

    if let Some(note) = tool_note {
        for line in note.lines() {
            out.push_str(&format!("{comment} {line}\n"));
        }
    }

    let mut device = String::new();
    if !job.serial.is_empty() {
        match shell {
            Shell::Cmd => out.push_str(&format!("set \"SERIAL={}\"\n", job.serial)),
            Shell::Sh => out.push_str(&format!("SERIAL={}\n", shell.quote(job.serial))),
        }

        device = match shell {
            Shell::Cmd => " -s \"%SERIAL%\"".to_owned(),
            Shell::Sh => " -s \"$SERIAL\"".to_owned(),
        };
    } else {
        out.push_str(&format!(
            "{comment} No device was selected, so the tool is left to pick the only one.\n"
        ));
    }

    let prefix = match shell {
        Shell::Cmd => format!("\"%MFASTBOOT%\"{device}"),
        Shell::Sh => format!("\"$MFASTBOOT\"{device}"),
    };

    // The procedures, in the order they run.
    out.push('\n');
    for step in job.steps {
        out.push_str(&format!("{prefix} {}\n", step_command(shell, step)));
    }

    // The standalone erases, last — like the app runs them.
    if !job.extra_erases.is_empty() {
        out.push('\n');
        out.push_str(&format!(
            "{comment} Extra erases, added in the dialog. A partition the device does not\n\
             {comment} have makes the tool print an error, which is not fatal.\n"
        ));

        for partition in job.extra_erases {
            out.push_str(&format!("{prefix} erase {partition}\n"));
        }
    }

    out
}

/// The command that starts the steps, plus a note for the header when it is
/// not simply the selected build.
fn tool_of(engine: &Engine) -> (String, Option<&'static str>) {
    match engine {
        Engine::Mfastboot(tool) => (tool.path.display().to_string(), None),
        // The built-in engine is part of the app, so a script can only use the
        // `fastboot` of the Android platform-tools.
        Engine::Builtin => (
            "fastboot".to_owned(),
            Some(
                "The built-in fastboot has no command line, so this script runs `fastboot`\n\
                 from the Android platform-tools: put it on PATH or edit the line above.",
            ),
        ),
    }
}

/// One procedure as the tool's arguments (`flash boot "boot.img"`).
fn step_command(shell: Shell, step: &FlashOp) -> String {
    match step {
        FlashOp::Flash {
            partition, file, ..
        } => format!("flash {partition} {}", shell.quote(file)),
        FlashOp::Erase { partition } => format!("erase {partition}"),
        FlashOp::Oem { var } => format!("oem {var}"),
        FlashOp::Getvar { var } => format!("getvar {var}"),
    }
}

/// Turns a phone model into something that can be part of a file name
/// (`XT2451-2` stays as it is, anything else becomes `_`).
fn sanitize(name: &str) -> String {
    name.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.') {
                character
            } else {
                '_'
            }
        })
        .collect::<String>()
        .trim_matches('_')
        .to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn package() -> FlashPackage {
        FlashPackage {
            directory: PathBuf::from("/firmware/arcfox"),
            flashfile: PathBuf::from("/firmware/arcfox/flashfile.xml"),
            model: Some("XT2451-2".to_owned()),
            software_version: Some("U1SJS34.72-35-3".to_owned()),
            cid: Some("0x0032".to_owned()),
            ignored_partitions: Vec::new(),
            steps: vec![
                FlashOp::Flash {
                    partition: "boot".to_owned(),
                    file: "boot.img".to_owned(),
                    md5: Some("abc".to_owned()),
                },
                FlashOp::Oem {
                    var: "config bootmode fastboot".to_owned(),
                },
                FlashOp::Getvar {
                    var: "max-sparse-size".to_owned(),
                },
                FlashOp::Erase {
                    partition: "userdata".to_owned(),
                },
            ],
        }
    }

    fn job<'a>(
        package: &'a FlashPackage,
        steps: &'a [FlashOp],
        extra_erases: &'a [String],
        engine: &'a Engine,
        serial: &'a str,
        shell: Shell,
    ) -> ScriptJob<'a> {
        ScriptJob {
            package,
            steps,
            extra_erases,
            engine,
            serial,
            shell,
        }
    }

    #[test]
    fn cmd_script_runs_the_selected_steps() {
        let package = package();
        let steps = vec![
            FlashOp::Flash {
                partition: "boot".to_owned(),
                file: "boot.img".to_owned(),
                md5: None,
            },
            FlashOp::Oem {
                var: "fb_mode_clear".to_owned(),
            },
        ];
        let extra = vec!["modemst1".to_owned(), "modemst2".to_owned()];
        let engine = Engine::Builtin;

        let script = render(&job(
            &package,
            &steps,
            &extra,
            &engine,
            "ZY22ABC",
            Shell::Cmd,
        ));

        assert!(script.starts_with("@echo off\n"));
        assert!(script.contains("cd /d \"/firmware/arcfox\"\n"));
        assert!(script.contains("set \"MFASTBOOT=fastboot\"\n"));
        assert!(script.contains("set \"SERIAL=ZY22ABC\"\n"));
        assert!(script.contains("\"%MFASTBOOT%\" -s \"%SERIAL%\" flash boot \"boot.img\"\n"));
        assert!(script.contains("\"%MFASTBOOT%\" -s \"%SERIAL%\" oem fb_mode_clear\n"));
        assert!(script.contains("\"%MFASTBOOT%\" -s \"%SERIAL%\" erase modemst2\n"));
        // Only the selected procedures, and no leftover of the others.
        assert!(!script.contains("getvar"));
    }

    #[test]
    fn sh_script_quotes_every_value() {
        let package = package();
        let steps = vec![FlashOp::Flash {
            partition: "boot".to_owned(),
            file: "boot image.img".to_owned(),
            md5: None,
        }];
        let engine = Engine::Mfastboot(crate::flash_engine::Mfastboot {
            version: "34.0.4".to_owned(),
            path: PathBuf::from("/opt/mfastboot 34/mfastboot"),
            emulator: crate::flash_engine::Emulator::Native,
        });

        let script = render(&job(&package, &steps, &[], &engine, "", Shell::Sh));

        assert!(script.starts_with("#!/bin/sh\n"));
        assert!(script.contains("MFASTBOOT=\"/opt/mfastboot 34/mfastboot\"\n"));
        assert!(script.contains("\"$MFASTBOOT\" flash boot \"boot image.img\"\n"));
        // No device selected: no `SERIAL` line and no `-s`.
        assert!(!script.contains("SERIAL="));
        assert!(!script.contains(" -s "));
    }

    #[test]
    fn file_names_follow_the_model_and_shell() {
        assert_eq!(Shell::Cmd.file_name(Some("XT2451-2")), "XT2451-2_flash.cmd");
        assert_eq!(Shell::Sh.file_name(Some("XT2451-2")), "XT2451-2_flash.sh");
        assert_eq!(Shell::Cmd.file_name(Some(" XT 2451 ")), "XT_2451_flash.cmd");
        assert_eq!(Shell::Cmd.file_name(None), "flash.cmd");
        assert_eq!(Shell::Sh.file_name(Some("")), "flash.sh");
    }

    #[test]
    fn the_host_decides_the_shell() {
        let expected = if cfg!(windows) { Shell::Cmd } else { Shell::Sh };

        assert_eq!(Shell::for_host(), expected);
    }
}
